[package]
name = "sdkwork-routes-webserver-common"
version.workspace = true
edition.workspace = true

[dependencies]
axum.workspace = true
serde.workspace = true
sdkwork-webserver-contract.workspace = true
sdkwork-webserver-http-host.workspace = true
sdkwork-utils-rust.workspace = true

[dev-dependencies]
serde_json.workspace = true
